import { Category, Subcategory, Calculator } from '../types';

export const CORE_MONEY_CATEGORY: Category = {
  id: 'cat_core_money',
  name: 'Core Money Calculators',
  slug: 'core-money-calculators',
  description: 'Core financial calculation categories covering mortgages, loans, investments, savings, and debt payoff.',
  icon: 'Coins',
  displayOrder: 1,
  isActive: true,
  seoTitle: 'Core Money Calculators | Financial & Calculation Categories',
  seoDescription: 'Explore core financial categories including mortgage, loan, compound interest, investment, retirement, and debt management.',
  seoKeywords: ['core money calculators', 'financial categories', 'finance tools'],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const CORE_MONEY_SUBCATEGORIES: Subcategory[] = [
  {
    id: 'sub_mortgage',
    categoryId: 'cat_core_money',
    name: 'Mortgage Calculator',
    slug: 'mortgage-calculator',
    description: 'Mortgage payment and home loan estimation tools.',
    icon: 'Home',
    displayOrder: 1,
    isActive: true,
    seoTitle: 'Mortgage Calculator Subcategory',
    seoDescription: 'Mortgage calculation category.',
    seoKeywords: ['mortgage calculator', 'home loan'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_loan',
    categoryId: 'cat_core_money',
    name: 'Loan Calculator',
    slug: 'loan-calculator',
    description: 'Fixed-rate loan and installment calculation tools.',
    icon: 'DollarSign',
    displayOrder: 2,
    isActive: true,
    seoTitle: 'Loan Calculator Subcategory',
    seoDescription: 'Loan calculation category.',
    seoKeywords: ['loan calculator', 'loan repayment'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_compound_interest',
    categoryId: 'cat_core_money',
    name: 'Compound Interest Calculator',
    slug: 'compound-interest-calculator',
    description: 'Compound interest and periodic growth simulation tools.',
    icon: 'TrendingUp',
    displayOrder: 3,
    isActive: true,
    seoTitle: 'Compound Interest Calculator Subcategory',
    seoDescription: 'Compound interest calculation category.',
    seoKeywords: ['compound interest calculator', 'apy interest'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_investment',
    categoryId: 'cat_core_money',
    name: 'Investment Calculator',
    slug: 'investment-calculator',
    description: 'Portfolio compounding and return on investment forecasting tools.',
    icon: 'PieChart',
    displayOrder: 4,
    isActive: true,
    seoTitle: 'Investment Calculator Subcategory',
    seoDescription: 'Investment calculation category.',
    seoKeywords: ['investment calculator', 'portfolio growth'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_retirement',
    categoryId: 'cat_core_money',
    name: 'Retirement Calculator',
    slug: 'retirement-calculator',
    description: 'Retirement nest egg planning and longevity tools.',
    icon: 'Award',
    displayOrder: 5,
    isActive: true,
    seoTitle: 'Retirement Calculator Subcategory',
    seoDescription: 'Retirement calculation category.',
    seoKeywords: ['retirement calculator', 'pension planner'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_savings',
    categoryId: 'cat_core_money',
    name: 'Savings Calculator',
    slug: 'savings-calculator',
    description: 'Target savings goal and interest accumulation tools.',
    icon: 'PiggyBank',
    displayOrder: 6,
    isActive: true,
    seoTitle: 'Savings Calculator Subcategory',
    seoDescription: 'Savings calculation category.',
    seoKeywords: ['savings calculator', 'emergency fund'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_auto_loan',
    categoryId: 'cat_core_money',
    name: 'Auto Loan Calculator',
    slug: 'auto-loan-calculator',
    description: 'Vehicle financing, trade-in, and monthly auto loan tools.',
    icon: 'Car',
    displayOrder: 7,
    isActive: true,
    seoTitle: 'Auto Loan Calculator Subcategory',
    seoDescription: 'Auto loan calculation category.',
    seoKeywords: ['auto loan calculator', 'car loan'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_personal_loan',
    categoryId: 'cat_core_money',
    name: 'Personal Loan Calculator',
    slug: 'personal-loan-calculator',
    description: 'Unsecured personal loan installment and APR tools.',
    icon: 'CreditCard',
    displayOrder: 8,
    isActive: true,
    seoTitle: 'Personal Loan Calculator Subcategory',
    seoDescription: 'Personal loan calculation category.',
    seoKeywords: ['personal loan calculator', 'unsecured loan'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_debt_payoff',
    categoryId: 'cat_core_money',
    name: 'Debt Payoff Calculator',
    slug: 'debt-payoff-calculator',
    description: 'Multi-account debt payoff, Avalanche, and Snowball strategy tools.',
    icon: 'TrendingDown',
    displayOrder: 9,
    isActive: true,
    seoTitle: 'Debt Payoff Calculator Subcategory',
    seoDescription: 'Debt payoff calculation category.',
    seoKeywords: ['debt payoff calculator', 'avalanche', 'snowball'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_credit_card_payoff',
    categoryId: 'cat_core_money',
    name: 'Credit Card Payoff Calculator',
    slug: 'credit-card-payoff-calculator',
    description: 'Revolving credit card balance payoff and interest elimination tools.',
    icon: 'Zap',
    displayOrder: 10,
    isActive: true,
    seoTitle: 'Credit Card Payoff Calculator Subcategory',
    seoDescription: 'Credit card payoff calculation category.',
    seoKeywords: ['credit card payoff calculator', 'credit card interest'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_mortgage',
    categoryId: 'cat_core_money',
    name: 'Mortgage Calculator',
    slug: 'mortgage-calculator',
    description: 'Home mortgage PITI, PMI thresholds, and HOA affordability tools.',
    icon: 'Home',
    displayOrder: 11,
    isActive: true,
    seoTitle: 'Mortgage Calculator Subcategory',
    seoDescription: 'Mortgage and home buying calculation tools.',
    seoKeywords: ['mortgage calculator', 'piti calculator', 'home buying'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const CORE_MONEY_CALCULATORS: Calculator[] = [
  {
    id: 'calc_credit_card_payoff',
    categoryId: 'cat_core_money',
    subcategoryId: 'sub_credit_card_payoff',
    name: 'Credit Card Payoff Calculator',
    slug: 'credit-card-payoff-calculator',
    shortDescription: 'Calculate your exact payoff schedule, total interest paid, and time to become credit card debt-free.',
    longDescription: 'Use this Credit Card Payoff Calculator to estimate how many months it will take to eliminate your card balance based on a fixed monthly payment.',
    formulaExplanation: 'Iterates month by month applying monthly rate (APR / 12), deducting accrued interest from your payment, and applying the remaining principal to the balance.',
    icon: 'CreditCard',
    displayOrder: 1,
    isActive: true,
    isFeatured: true,
    isPopular: true,
    viewCount: 120,
    seoTitle: 'Credit Card Payoff Calculator | Calculate Payoff Schedule & Interest',
    seoDescription: 'Find out how long it will take to pay off your credit card balance and how much interest you can save with fixed monthly payments.',
    seoKeywords: ['credit card payoff calculator', 'credit card payment calculator', 'credit card interest', 'pay off credit card'],
    config: {
      inputs: [
        {
          id: 'balance',
          label: 'Current Card Balance',
          type: 'currency',
          defaultValue: 5000,
          min: 1,
          step: 10,
          helpText: 'The current outstanding balance on your credit card.',
          required: true,
        },
        {
          id: 'apr',
          label: 'Interest Rate (APR %)',
          type: 'percentage',
          defaultValue: 21.99,
          min: 0.1,
          max: 99.99,
          step: 0.01,
          helpText: 'Your annual percentage rate.',
          required: true,
        },
        {
          id: 'monthlyPayment',
          label: 'Fixed Monthly Payment',
          type: 'currency',
          defaultValue: 200,
          min: 1,
          step: 10,
          helpText: 'The fixed amount you plan to pay toward the balance each month.',
          required: true,
        },
      ],
      outputs: [
        {
          id: 'timeToPayOff',
          label: 'Time to Pay Off',
          formula: 'months',
          format: 'text',
          isMainResult: true,
          description: 'Total time required to completely eliminate the card balance.',
        },
        {
          id: 'totalInterest',
          label: 'Total Interest Paid',
          formula: 'interest',
          format: 'currency',
          description: 'Cumulative finance charges paid over the entire payoff duration.',
        },
        {
          id: 'totalPaid',
          label: 'Total Amount Paid',
          formula: 'total',
          format: 'currency',
          description: 'Principal balance plus cumulative interest.',
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'calc_personal_loan',
    categoryId: 'cat_core_money',
    subcategoryId: 'sub_personal_loan',
    name: 'Personal Loan Calculator',
    slug: 'personal-loan-calculator',
    shortDescription: 'Estimate your monthly payments, total interest costs, and amortization breakdown for personal loans.',
    longDescription: 'Use this Personal Loan Calculator to estimate monthly installments and total borrowing costs based on loan principal, fixed interest rate (APR), and loan term.',
    formulaExplanation: 'Calculates fixed amortized monthly payments using M = P * [r(1+r)^n] / [(1+r)^n - 1] where r is the monthly rate and n is the loan term in months.',
    icon: 'DollarSign',
    displayOrder: 2,
    isActive: true,
    isFeatured: true,
    isPopular: true,
    viewCount: 95,
    seoTitle: 'Personal Loan Calculator | Monthly Payment & Interest Breakdown',
    seoDescription: 'Calculate monthly loan payments, total interest charges, and loan amortization schedule for unsecured personal loans.',
    seoKeywords: ['personal loan calculator', 'loan payment calculator', 'personal loan apr', 'loan amortization'],
    config: {
      inputs: [
        {
          id: 'loanAmount',
          label: 'Loan Amount',
          type: 'currency',
          defaultValue: 15000,
          min: 1000,
          max: 100000,
          step: 500,
          helpText: 'The total principal borrowed ($1,000 to $100,000).',
          required: true,
        },
        {
          id: 'interestRate',
          label: 'Interest Rate (APR %)',
          type: 'percentage',
          defaultValue: 11.5,
          min: 1,
          max: 36,
          step: 0.1,
          helpText: 'Your fixed annual interest rate.',
          required: true,
        },
        {
          id: 'loanTerm',
          label: 'Loan Term',
          type: 'select',
          defaultValue: 36,
          options: [
            { label: '1 Year (12 months)', value: 12 },
            { label: '2 Years (24 months)', value: 24 },
            { label: '3 Years (36 months)', value: 36 },
            { label: '4 Years (48 months)', value: 48 },
            { label: '5 Years (60 months)', value: 60 },
            { label: '6 Years (72 months)', value: 72 },
            { label: '7 Years (84 months)', value: 84 },
          ],
          helpText: 'Repayment duration in months.',
          required: true,
        },
      ],
      outputs: [
        {
          id: 'monthlyPayment',
          label: 'Estimated Monthly Payment',
          formula: 'payment',
          format: 'currency',
          isMainResult: true,
          description: 'Fixed installment due each month.',
        },
        {
          id: 'totalPrincipal',
          label: 'Total Principal',
          formula: 'principal',
          format: 'currency',
          description: 'Total borrowed loan principal.',
        },
        {
          id: 'totalInterest',
          label: 'Total Interest Paid',
          formula: 'interest',
          format: 'currency',
          description: 'Total finance interest paid over the life of the loan.',
        },
        {
          id: 'totalCost',
          label: 'Total Loan Cost',
          formula: 'total',
          format: 'currency',
          description: 'Sum of principal plus total interest paid.',
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'calc_debt_snowball_avalanche',
    categoryId: 'cat_core_money',
    subcategoryId: 'sub_debt_payoff',
    name: 'Debt Snowball vs. Avalanche Calculator',
    slug: 'debt-snowball-vs-avalanche-calculator',
    shortDescription: 'Compare psychological quick-wins (Snowball) against maximum interest savings (Avalanche) across multiple debts.',
    longDescription: 'Multi-debt payoff aggregator that compares the Debt Snowball and Debt Avalanche strategies side-by-side to calculate interest savings and payoff timelines.',
    formulaExplanation: 'Simulates multi-debt amortization month-by-month, rolling over minimum payments of eliminated debts into the next target debt according to snowball or avalanche ordering.',
    icon: 'TrendingDown',
    displayOrder: 3,
    isActive: true,
    isFeatured: true,
    isPopular: true,
    viewCount: 150,
    seoTitle: 'Debt Snowball vs. Avalanche Calculator | Compare Payoff Strategies',
    seoDescription: 'Multi-debt payoff aggregator that compares the Debt Snowball and Debt Avalanche strategies side-by-side to calculate interest savings and payoff timelines.',
    seoKeywords: ['debt snowball calculator', 'debt avalanche calculator', 'debt payoff strategy', 'interest savings'],
    config: {
      inputs: [],
      outputs: [],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'calc_compound_interest',
    categoryId: 'cat_core_money',
    subcategoryId: 'sub_compound_interest',
    name: 'Compound Interest Calculator',
    slug: 'compound-interest-calculator',
    shortDescription: 'Model long-term wealth accumulation with step-up deposits, compounding intervals, tax drag, and inflation adjustment.',
    longDescription: 'Use this Compound Interest Calculator to simulate interest accumulation over time with recurring deposits, step-up escalation, tax drag, and inflation modeling.',
    formulaExplanation: 'Calculates future value using annuity due and ordinary annuity compound formulas combined with step-up deposit escalation.',
    icon: 'TrendingUp',
    displayOrder: 4,
    isActive: true,
    isFeatured: true,
    isPopular: true,
    viewCount: 180,
    seoTitle: 'Compound Interest Calculator | Free APY Investment Growth Tool',
    seoDescription: 'Calculate compound interest growth, interest tipping point, and inflation-adjusted future portfolio value.',
    seoKeywords: ['compound interest calculator', 'investment calculator', 'compound growth', 'apy calculator'],
    config: {
      inputs: [],
      outputs: [],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'calc_auto_loan',
    categoryId: 'cat_core_money',
    subcategoryId: 'sub_auto_loan',
    name: 'Auto Loan Calculator',
    slug: 'auto-loan-calculator',
    shortDescription: 'Calculate your monthly auto loan payment, trade-in equity, total interest paid, and early payoff savings.',
    longDescription: 'Use this Auto Loan Calculator to estimate monthly car payments, total loan interest, and sales tax based on vehicle purchase price, down payment, trade-in value, and loan terms.',
    formulaExplanation: 'Calculates amortized monthly payments M = P * [r(1+r)^n] / [(1+r)^n - 1] accounting for down payments, trade-in equity, sales tax, and dealer fees.',
    icon: 'Car',
    displayOrder: 5,
    isActive: true,
    isFeatured: true,
    isPopular: true,
    viewCount: 210,
    seoTitle: 'Auto Loan Calculator | Estimate Monthly Payment, Trade-In & Interest',
    seoDescription: 'Free Auto Loan Calculator to estimate monthly car payments, total loan cost, sales tax, and amortization schedules.',
    seoKeywords: ['auto loan calculator', 'car loan calculator', 'monthly car payment', 'trade in calculator', 'auto loan rate'],
    config: {
      inputs: [],
      outputs: [],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'calc_mortgage',
    categoryId: 'cat_core_money',
    subcategoryId: 'sub_mortgage',
    name: 'Mortgage Calculator',
    slug: 'mortgage-calculator',
    shortDescription: 'Calculate your monthly mortgage PITI payment, property taxes, home insurance, PMI, and HOA fees.',
    longDescription: 'Use this Advanced Mortgage Calculator to estimate monthly housing costs, PITI component breakdown, Private Mortgage Insurance cancellation timelines, and custom interest rate buy-down programs.',
    formulaExplanation: 'Calculates monthly Principal & Interest payment using the compound amortization formula, adding property tax, home insurance, PMI (if down payment < 20%), and monthly HOA fees.',
    icon: 'Home',
    displayOrder: 6,
    isActive: true,
    isFeatured: true,
    isPopular: true,
    viewCount: 320,
    seoTitle: 'Mortgage Calculator | Calculate PITI, PMI & Interest Savings',
    seoDescription: 'Free online Mortgage Calculator to estimate PITI payments, HOA fees, PMI cancellation schedules, and accelerated principal payoff timelines.',
    seoKeywords: ['mortgage calculator', 'piti calculator', 'home loan payment', 'pmi calculator', 'mortgage amortization'],
    config: {
      inputs: [],
      outputs: [],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
