import React from 'react';
import {
  Calculator,
  DollarSign,
  Percent,
  HeartPulse,
  Activity,
  Scale,
  TrendingUp,
  Coins,
  Briefcase,
  GraduationCap,
  Flame,
  ShieldCheck,
  Cpu,
  Zap,
  Compass,
  PieChart,
  Clock,
  Sliders,
  Calendar,
  Award,
  Sparkles,
  Layers,
  Building,
  Car,
  Home,
  Utensils,
  Plane,
  ShoppingBag,
  Stethoscope,
  Weight,
  Thermometer,
  Wrench,
  Boxes,
  HelpCircle,
  LucideProps,
} from 'lucide-react';

export const AVAILABLE_ICONS: Record<string, React.FC<LucideProps>> = {
  Calculator,
  DollarSign,
  Percent,
  HeartPulse,
  Activity,
  Scale,
  TrendingUp,
  Coins,
  Briefcase,
  GraduationCap,
  Flame,
  ShieldCheck,
  Cpu,
  Zap,
  Compass,
  PieChart,
  Clock,
  Sliders,
  Calendar,
  Award,
  Sparkles,
  Layers,
  Building,
  Car,
  Home,
  Utensils,
  Plane,
  ShoppingBag,
  Stethoscope,
  Weight,
  Thermometer,
  Wrench,
  Boxes,
};

export function getDynamicIcon(iconName?: string, props: LucideProps = { className: 'w-5 h-5' }) {
  if (!iconName) {
    return <Calculator {...props} />;
  }
  const IconComponent = AVAILABLE_ICONS[iconName] || Calculator;
  return <IconComponent {...props} />;
}
